auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
   working_directory: /tmp/loki/compactor #/var/loki/retention
   compaction_interval: 10m
   retention_enabled: true
   retention_delete_delay: 2h #672h   # 28 days
   retention_delete_worker_count: 150
   delete_request_store: s3

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/cache/index
    cache_location: /tmp/loki/cache/index_cache
    cache_ttl: 24h
  aws:
    s3: s3://minioadmin:supersecret@minio:9000/loki
    endpoint: http://minio:9000
    s3forcepathstyle: true
    access_key_id: "minioadmin"
    secret_access_key: "supersecret"
    insecure: true
    region: null
    sse_encryption: false
    http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: true

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
